language: php

matrix:
    include:
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: nightly
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-3.12
        - php: hhvm-nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: scripts/travis
after_script: scripts/travis-after
deploy:
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.0'
          branch: master
    - provider: script
      script: make publish
      skip_cleanup: true
      on:
          php: '7.0'
          tags: true

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.0
        - secure: "r6z/HhH6q8e4AhED4/LuhjqudMqiOcMV2NThaqSSH6vDU/LHNA38o1dpemsHKSqpxW38kIIBM8x0apWBdbxEjwPoLwsIq5uZQPoyP01sa0MiZNyXhozxvu+v+vtiBh4A1kZtkeyXDd3hYLGHLI9Q5AyRPen9lZzHlTc42xivcEvf73pZAjFaGcbq/Hv54cZqBPxqCquLeGechKf1dcOPlWjH33rET3M4m0FarcJ36buQfvQ9wJQy9C/gV+b51UR8MVZgtZRiMJgs++ObR1ZYo4AJGGdOGTjBsbOe+iwtz3prVGzOhoC4rhssjow+/TGZwlRhHkjdCh8MJEWumnVtm0ySBMvUsmFIZvaOM6QI5oaQsJSAuyM5iTfrWDwbjhYk8z5gjOrdSwMDt9Hqj15tjfE4JEPzHzLKZPRbncZrw6onWd3210BuqSdDKYb93KW6dY+Dma9Q2RrGdZbFaUvsQvyKYB97K7H6hm8CgfetEnleVh5JHKltG+0f8BbuvtzEFG1PasvsRnjuMJeE04M3Dbb73kVMr3MDazSjQzkY5CBkyZLvVhYZj2tZyQuEsEBwHFwV8J7L/bhxYyZLc1D+y6A66kjPnSzJzlekzJqgxWuJaZEql0h4k7HHvWEs/1t9B0ShT8qGYGqcmB2OI9b14ZrR2YEsacvg0IEQTNqhVco="

cache:
    directories:
        - $HOME/.composer

sudo: false
